server:
  port: 0

spring:
  application:
    name: pos-delivery
  cloud:
    function:
      definition: orderDeliver
    stream:
      function:
        bindings:
          orderDeliver-in-0: OrderDeliverer
      bindings:
        order-approved:
          destination: order-approved
      rabbit:
        bindings:
          output:
            consumer:
              declare-exchange: false